In [1]:
#Github Link:https://github.com/arpit-shrivastava-2020/Deep-Learning-1st-Lab-Assignment.git

In [2]:
print("Code by Arpit Shrivastava, Registration No.:(20MAI0068)")

Code by Arpit Shrivastava, Registration No.:(20MAI0068)


In [3]:
import pandas as pd
import numpy as np
iris=pd.read_csv("iris.csv")

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris=load_iris()
datasets = train_test_split(iris.data,iris.target,test_size=0.1)
train_data, test_data, train_labels, test_labels = datasets

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_data)
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)
print(train_data[:3])

[[-0.03608662 -0.77757055  0.75683817  0.89471929]
 [-1.1603235   0.1472931  -1.31774362 -1.49185357]
 [-0.91049308  1.76580449 -1.26011635 -1.35926619]]


In [6]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [7]:
from sklearn.metrics import accuracy_score
predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

0.9703703703703703
1.0


In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(predictions_train, train_labels)

array([[43,  0,  0],
       [ 0, 42,  1],
       [ 0,  3, 46]], dtype=int64)

In [9]:
confusion_matrix(predictions_test, test_labels)

array([[7, 0, 0],
       [0, 5, 0],
       [0, 0, 3]], dtype=int64)

In [10]:
from sklearn.metrics import classification_report
print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [11]:
import pandas as pd
dataset=load_iris()
data=pd.DataFrame(dataset['data'],columns=['Petal length','Petal Width','Sepal Length','Sepal Width'])

In [12]:
data.head()

Petal length  Petal Width  Sepal Length  Sepal Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [13]:
data.tail()

Petal length  Petal Width  Sepal Length  Sepal Width
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [14]:
data.shape

(150, 4)

In [15]:
datasets = train_test_split(iris.data, iris.target,test_size=0.2)
train_data, test_data, train_labels, test_labels = datasets

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(train_data)

StandardScaler()

In [18]:
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)
print(train_data[:3])

[[ 0.65505494  0.43979635  0.40240947  0.37217444]
 [-0.92192917 -1.20211001 -0.45479413 -0.15792565]
 [ 1.26158729  0.2052383   0.74529091  1.43237463]]


In [19]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [20]:
predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

0.975
0.9666666666666667


In [21]:
confusion_matrix(predictions_train, train_labels)

array([[38,  0,  0],
       [ 0, 37,  1],
       [ 0,  2, 42]], dtype=int64)

In [22]:
confusion_matrix(predictions_test, test_labels)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  7]], dtype=int64)

In [23]:
print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      1.00      0.95        10
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [24]:
datasets = train_test_split(iris.data, iris.target,test_size=0.3)
train_data, test_data, train_labels, test_labels = datasets

In [25]:
scaler = StandardScaler()
scaler.fit(train_data)

StandardScaler()

In [26]:
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)
print(train_data[:3])

[[-0.03524015 -0.74819867  0.76591533  0.94197211]
 [-0.51268739  1.84171981 -1.0979686  -0.99485044]
 [ 0.20348347 -0.74819867  0.76591533  0.5546076 ]]


In [27]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [28]:
predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

0.9809523809523809
0.9777777777777777


In [29]:
confusion_matrix(predictions_train, train_labels)

array([[38,  0,  0],
       [ 0, 29,  1],
       [ 0,  1, 36]], dtype=int64)

In [30]:
confusion_matrix(predictions_test, test_labels)

array([[12,  0,  0],
       [ 0, 19,  0],
       [ 0,  1, 13]], dtype=int64)

In [31]:
print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.95      1.00      0.97        19
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [32]:
datasets = train_test_split(iris.data, iris.target,test_size=0.4)
train_data, test_data, train_labels, test_labels = datasets

In [33]:
scaler = StandardScaler()
scaler.fit(train_data)

StandardScaler()

In [34]:
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)
print(train_data[:3])

[[-0.56666446  0.77187062 -1.2975083  -1.05949819]
 [ 0.78513751  0.32368768  0.78364363  1.11073992]
 [ 1.64537513  0.32368768  1.30393161  0.83946016]]


In [35]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [36]:
predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

0.9777777777777777
0.9666666666666667


In [37]:
confusion_matrix(predictions_train, train_labels)

array([[29,  0,  0],
       [ 0, 32,  1],
       [ 0,  1, 27]], dtype=int64)

In [38]:
confusion_matrix(predictions_test, test_labels)

array([[20,  0,  0],
       [ 1, 16,  0],
       [ 0,  1, 22]], dtype=int64)

In [39]:
print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98        20
           1       0.94      0.94      0.94        17
           2       1.00      0.96      0.98        23

    accuracy                           0.97        60
   macro avg       0.96      0.97      0.96        60
weighted avg       0.97      0.97      0.97        60



In [40]:
datasets = train_test_split(iris.data, iris.target,test_size=0.5)
train_data, test_data, train_labels, test_labels = datasets

In [41]:
scaler = StandardScaler()
scaler.fit(train_data)

StandardScaler()

In [42]:
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)
print(train_data[:3])

[[-0.22540926 -0.54769114  0.15078683  0.08871591]
 [ 0.24419336 -0.99908494  1.00322493  0.21918049]
 [-1.28201514  0.12939956 -1.26994334 -1.34639445]]


In [43]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)
mlp.fit(train_data, train_labels)

MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000)

In [44]:
predictions_train = mlp.predict(train_data)
print(accuracy_score(predictions_train, train_labels))
predictions_test = mlp.predict(test_data)
print(accuracy_score(predictions_test, test_labels))

1.0
0.9466666666666667


In [45]:
confusion_matrix(predictions_train, train_labels)

array([[23,  0,  0],
       [ 0, 24,  0],
       [ 0,  0, 28]], dtype=int64)

In [46]:
confusion_matrix(predictions_test, test_labels)

array([[27,  0,  0],
       [ 0, 22,  0],
       [ 0,  4, 22]], dtype=int64)

In [47]:
print(classification_report(predictions_test, test_labels))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.85      1.00      0.92        22
           2       1.00      0.85      0.92        26

    accuracy                           0.95        75
   macro avg       0.95      0.95      0.94        75
weighted avg       0.95      0.95      0.95        75

